---
# Node Exporter 設定
node_exporter_version: 1.9.1
# 修改 Node Exporter 監聽地址，監聽所有網絡介面
node_exporter_web_listen_address: 0.0.0.0:9100
node_exporter_enabled_collectors:
  - filesystem
  - diskstats
  - cpu
  - meminfo
  - netdev
  - loadavg
  - processes
  - systemd

# DCGM Exporter 設定
dcgm_exporter_version: 4.2.0-4.1.0-ubuntu22.04
dcgm_exporter_port: 9400
dcgm_exporter_firewall_allow_from:
  - "{{ hostvars[groups['monitoring'][0]].ansible_host }}" # 允許監控伺服器的私有 IP 訪問
  - "{{vault_monitoring_public_ip}}" # 添加監控伺服器的公共 IP 地址
dcgm_exporter_image: nvcr.io/nvidia/k8s/dcgm-exporter:{{ dcgm_exporter_version }}
dcgm_exporter_dir: /opt/dcgm-exporter

# Prometheus 和 Grafana 設定
prometheus_version: v3.3.0
prometheus_retention_time: 15d
prometheus_scrape_interval: 15s
prometheus_evaluation_interval: 15s
prometheus_storage_path: /prometheus
prometheus_port: 9090
# 添加 Prometheus 身份驗證設定
prometheus_basic_auth_enabled: true
prometheus_basic_auth_username: "{{ vault_prometheus_username }}"
prometheus_basic_auth_password: "{{ vault_prometheus_password }}" # 使用 ansible-vault 加密的密碼

grafana_version: 11.6.1
grafana_port: 3000
grafana_admin_user: "{{ vault_grafana_username }}" # 使用 ansible-vault 加密的用戶名
grafana_admin_password: "{{ vault_grafana_password }}" # 使用 ansible-vault 加密的密碼
# 添加 Grafana 安全設定
grafana_security_admin_user: "{{ grafana_admin_user }}"
grafana_security_admin_password: "{{ grafana_admin_password }}"
grafana_security_disable_gravatar: "false"
grafana_security_cookie_secure: "true"
grafana_security_cookie_samesite: lax
grafana_users_allow_sign_up: "false"
grafana_auth_anonymous_enabled: "false"
grafana_auth_anonymous_org_name: Main Org.
grafana_auth_anonymous_org_role: Viewer
grafana_auth_anonymous_hide_version: "true"
grafana_auth_generic_oauth_tls_skip_verify_insecure: "false"
# Grafana HTTPS 配置
grafana_protocol: https
grafana_cert_path: /etc/grafana/certs/grafana.crt
grafana_cert_key: /etc/grafana/certs/grafana.key
grafana_server_domain: "{{vault_grafana_server_domain}}"
grafana_server_root_url: "{{vault_grafana_server_root_url}}"
grafana_strict_transport_security: "false"

# Monitoring SSL
monitoring_organization: SMIL
monitoring_country: TW

# Monitoring 伺服器設定
monitoring_data_dir: /opt/monitoring

# Node Exporter 防火牆設定
node_exporter_firewall_allow_from:
  - "{{ hostvars[groups['monitoring'][0]].ansible_host }}" # 允許監控伺服器的私有 IP 訪問
  - "{{vault_monitoring_public_ip}}" # 添加監控伺服器的公共 IP 地址
# NUT Exporter 設定
nut_exporter_enabled: true
nut_exporter_version: 3.2.0
nut_exporter_port: 9199
nut_exporter_user: "{{ vault_nut_exporter_user }}"
nut_exporter_password: "{{ vault_nut_exporter_password }}"
nut_exporter_variables: >-
  battery.charge,battery.runtime,battery.voltage,battery.voltage.nominal,input.voltage,input.voltage.nominal,output.voltage,ups.load,ups.status,ups.realpower.nominal
