---
- name: Restart node_exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: restarted

- name: Reload ufw
  ansible.builtin.command: ufw reload
  when: ansible_os_family == "Debian"

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
