{
 "title": "GPU Summary",
 "description": "This dashboard is to display the metrics from DCGM Exporter and summary of all the GPUs",
 "tags": [
  "gpu",
  "monitoring",
  "DCGM"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_TEMP{job=\"$job\"},instance)"
    }
   },
   {
    "name": "gpu",
    "query": "label_values(DCGM_FI_DEV_GPU_TEMP, gpu)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_TEMP,job)"
    }
   }
  ]
 },
 "panels": [
  { "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 } },
  { "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 } },
  {
   "title": "GPU Power Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(DCGM_FI_DEV_POWER_USAGE{instance=~\"$instance\", gpu=~\"$gpu\"}, \"instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{instance}} GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Power Total",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_POWER_USAGE{instance=~\"$instance\", gpu=~\"$gpu\"})"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "stat",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(DCGM_FI_DEV_GPU_TEMP{instance=~\"$instance\", gpu=~\"$gpu\"}, \"instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{instance}} GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Avg. Temp",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_TEMP{instance=~\"$instance\", gpu=~\"$gpu\"})"
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU SM Clocks",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "hertz" } },
     "targets": [
      {
       "expr": "label_replace(DCGM_FI_DEV_SM_CLOCK{instance=~\"$instance\", gpu=~\"$gpu\"} * 1000000, \"instance\", \"$1\", \"instance\", \"([^:]+):\\\\d+\")",
       "legendFormat": "{{instance}} GPU {{gpu}}"
      }
     ]
    },
    {
     "title": "GPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "label_replace(DCGM_FI_DEV_GPU_UTIL{instance=~\"$instance\", gpu=~\"$gpu\"}, \"instance\", \"$1\", \"instance\", \"([^:]+):\\\\d+\")",
       "legendFormat": "{{instance}} GPU {{gpu}}"
      }
     ]
    },
    {
     "title": "GPU Framebuffer Mem Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "label_replace(DCGM_FI_DEV_FB_USED{instance=~\"$instance\", gpu=~\"$gpu\"},\"instance\", \"$1\", \"instance\", \"([^:]+):\\\\d+\")",
       "legendFormat": "{{instance}} GPU {{gpu}}"
      }
     ]
    }
   ]
  }
 ]
}