{
 "title": "GPU Single Host",
 "description": "Show the details of GPUs on a host",
 "tags": [
  "gpu",
  "monitoring",
  "DCGM"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_UTIL{job=\"$job\"},instance)"
    }
   },
   {
    "name": "gpu",
    "label": "GPU",
    "query": {
     "query": "label_values(DCGM_FI_DEV_DEC_UTIL{instance=\"$instance\"},gpu)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_TEMP,job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$instance GPU $gpu", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "gpu" },
  {
   "title": "GPU 使用率",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(DCGM_FI_DEV_GPU_UTIL{instance=\"$instance\", gpu=\"$gpu\"}, \"instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{instance}} GPU {{gpu}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{instance=\"$instance\", gpu=\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU 型號",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{instance=\"$instance\", gpu=\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU 溫度",
   "type": "gauge",
   "description": "GPU溫度",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{instance=\"$instance\", gpu=\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "記憶體總量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_FREE{instance=\"$instance\", gpu=\"$gpu\"} + DCGM_FI_DEV_FB_USED{instance=\"$instance\", gpu=\"$gpu\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU 記憶體使用率",
   "type": "bargauge",
   "description": "記憶體使用百分比",
   "gridPos": { "h": 2, "w": 19, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(DCGM_FI_DEV_FB_USED{instance=\"$instance\", gpu=\"$gpu\"},\"instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{instance}} GPU {{gpu}}"
    },
    {
     "expr": "DCGM_FI_DEV_FB_FREE{instance=\"$instance\", gpu=\"$gpu\"} + DCGM_FI_DEV_FB_USED{instance=\"$instance\"}",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}