---
collections:
  - name: community.general
    version: 10.6.0
  - name: community.docker
    version: 4.5.2
  - name: community.crypto
    version: 2.26.1
  - name: prometheus.prometheus
    version: 0.27.0
