---
- name: 安裝 Node Exporter 到所有節點
  hosts: nodes
  tags: node_exporter
  roles:
    - node_exporter

- name: 安裝 DCGM-Exporter 到所有節點
  hosts: nodes
  tags: dcgm_exporter
  roles:
    - dcgm_exporter

- name: Configure IPMI exporter
  hosts: ipmi
  tags: ipmi_exporter
  tasks:
    - name: Create sudoers file
      ansible.builtin.copy:
        src: ipmi_exporter.sudoers
        dest: /etc/sudoers.d/ipmi_exporter
        mode: '0400'

- name: Install IPMI Exporter Locally
  hosts: ipmi
  tags: ipmi_exporter
  roles:
    - prometheus.prometheus.ipmi_exporter
  vars:
    ipmi_exporter_modules:
      default:
        collectors:
          - bmc
          - ipmi
          - dcmi
          - chassis
          - sel
    ipmi_exporter_system_user: root
    ipmi_exporter_system_group: root

- name: 安裝 Prometheus 和 Grafana 到監控伺服器
  hosts: monitoring
  connection: local
  tags: monitoring
  roles:
    - monitoring
