---

- name: 安裝 Docker (Debian/Ubuntu)
  when:
    - ansible_os_family == "Debian"
  block:
    - name: 添加 Docker 儲存庫
      deb822_repository:
        name: docker
        types: [deb]
        uris: https://download.docker.com/linux/{{ ansible_distribution | lower }}
        suites: ["{{ ansible_distribution_release }}"]
        components: stable
        architectures: amd64
        signed_by: https://download.docker.com/linux/ubuntu/gpg

    - name: 更新 apt 快取
      apt:
        update_cache: yes

    - name: 安裝 Docker 套件
      apt:
        name:
          - docker-ce
          - docker-compose
        state: present

    - name: 安裝 Docker Python 模組
      pip:
        name: docker
        executable: pip3

- name: 啟動 Docker 服務
  systemd:
    name: docker
    state: started
    enabled: yes

- name: 拉取 ipmi-exporter Docker 映像
  community.general.docker_image:
    name: "{{ ipmi_exporter_image }}"
    source: pull
    force_source: yes

- name: 檢查現有的 IPMI-Exporter 容器
  command: docker ps -a --filter name=ipmi-exporter -q
  register: ipmi_exporter_container
  changed_when: false

- name: 移除現有的 IPMI-Exporter 容器
  command: docker rm -f ipmi-exporter
  when: ipmi_exporter_container.stdout != ""
  failed_when: false
  changed_when: ipmi_exporter_container.stdout != ""

- name: 運行 IPMI-Exporter Docker 容器
  community.docker.docker_container:
    name: ipmi-exporter
    image: "{{ ipmi_exporter_image }}"
    restart_policy: always
    state: started
    published_ports:
      - "{{ ipmi_exporter_port }}:9290"

- name: Drop other traffic
  ansible.builtin.iptables:
    chain: DOCKER-USER
    action: insert
    protocol: tcp
    destination_port: "{{ ipmi_exporter_port }}"
    jump: DROP
    state: present

- name: Allow trusted IPs to container port
  ansible.builtin.iptables:
    chain: DOCKER-USER
    action: insert
    protocol: tcp
    destination_port: "{{ ipmi_exporter_port }}"
    source: "{{ item }}"
    jump: ACCEPT
    state: present
  loop: "{{ ipmi_exporter_firewall_allow_from }}"


- name: 啟動 Docker 服務
  systemd:
    name: docker
    state: started
    enabled: yes
