---
- name: 安裝基本必備工具
  package:
    name:
      - python3-pip
      - docker
      - docker-compose
    state: present
  when: ansible_os_family == "Debian"

- name: 確保 Docker 服務已啟動並啟用
  systemd:
    name: docker
    state: started
    enabled: yes

- name: 安裝 Docker Python 模組
  pip:
    name: docker
    state: present

- name: 創建監控服務目錄
  file:
    path: "{{ monitoring_data_dir }}"
    state: directory
    mode: 0755

- name: 創建 Prometheus 數據目錄
  file:
    path: "{{ monitoring_data_dir }}/prometheus"
    state: directory
    mode: 0755
    owner: 65534  # nobody user
    group: 65534  # nobody group

# 為 Prometheus 創建 TLS 證書目錄
- name: 創建 Prometheus 證書目錄
  file:
    path: "{{ monitoring_data_dir }}/prometheus/certs"
    state: directory
    mode: 0750
    owner: 65534  # nobody user
    group: 65534  # nobody group

- name: Create private key (RSA) with password protection
  community.crypto.openssl_privatekey:
    path: "{{ monitoring_data_dir }}/prometheus/certs/server.key"
    type: RSA
    mode: 0640
    owner: 65534  # nobody user
    group: 65534  # nobody group

- name: Create certificate signing request (CSR) for self-signed certificate
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ monitoring_data_dir }}/prometheus/certs/server.key"
    common_name: prometheus.local
    organization_name: "{{ monitoring_organization }}"
    country_name: "{{ monitoring_country }}"
    subject_alt_name:
      - DNS:prometheus.local
  register: csr

- name: Create self-signed certificate from CSR
  community.crypto.x509_certificate:
    path: "{{ monitoring_data_dir }}/prometheus/certs/server.crt"
    csr_content: "{{ csr.csr }}"
    privatekey_path: "{{ monitoring_data_dir }}/prometheus/certs/server.key"
    provider: selfsigned
    mode: 0640
    owner: 65534  # nobody user
    group: 65534  # nobody group

# 為 Grafana 創建 TLS 證書目錄
- name: 創建 Grafana 證書目錄
  file:
    path: "{{ monitoring_data_dir }}/grafana/certs"
    state: directory
    mode: 0750
    owner: 472  # grafana user
    group: 472  # grafana group
- name: Create private key (RSA) with password protection
  community.crypto.openssl_privatekey:
    path: "{{ monitoring_data_dir }}/grafana/certs/grafana.key"
    type: RSA
    mode: 0640
    owner: 472  # grafana user
    group: 472  # grafana group

- name: Create certificate signing request (CSR) for self-signed certificate
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ monitoring_data_dir }}/grafana/certs/grafana.key"
    common_name: "{{ grafana_server_domain }}"
    organization_name: "{{ monitoring_organization }}"
    country_name: "{{ monitoring_country }}"
    subject_alt_name:
      - DNS:{{ grafana_server_domain }}
  register: csr

- name: Create self-signed certificate from CSR
  community.crypto.x509_certificate:
    path: "{{ monitoring_data_dir }}/grafana/certs/grafana.crt"
    csr_content: "{{ csr.csr }}"
    privatekey_path: "{{ monitoring_data_dir }}/grafana/certs/grafana.key"
    provider: selfsigned
    mode: 0640
    owner: 472  # grafana user
    group: 472  # grafana group

# 複製 Prometheus 身份驗證配置
- name: 複製 Prometheus 身份驗證配置
  template:
    src: web.yml.j2
    dest: "{{ monitoring_data_dir }}/prometheus/web.yml"
    mode: 0640
    owner: 65534  # nobody user
    group: 65534  # nobody group
  notify: Restart monitoring stack

# 複製 Prometheus 主配置文件
- name: 複製 Prometheus 配置文件
  template:
    src: prometheus.yml.j2
    dest: "{{ monitoring_data_dir }}/prometheus/prometheus.yml"
    mode: 0644
    owner: 65534  # nobody user
    group: 65534  # nobody group
  notify: Restart monitoring stack

- name: 創建 Grafana 數據目錄
  file:
    path: "{{ monitoring_data_dir }}/grafana"
    state: directory
    mode: 0755
    owner: 472  # grafana user
    group: 472  # grafana group

# 更新 Grafana 資料源配置，新增身份驗證資訊
- name: 確保 Grafana 佈建目錄存在
  file:
    path: "{{ monitoring_data_dir }}/grafana/provisioning/datasources"
    state: directory
    mode: 0755
    owner: 472
    group: 472

- name: 複製 Grafana 資料源配置
  template:
    src: datasource.yml.j2
    dest: "{{ monitoring_data_dir }}/grafana/provisioning/datasources/datasource.yml"
    mode: 0644
  register: grafana_datasource

- name: 確保 Grafana Dashboard 佈建目錄存在
  file:
    path: "{{ monitoring_data_dir }}/grafana/provisioning/dashboards"
    state: directory
    mode: 0755
    owner: 472
    group: 472

- name: 複製 Grafana Dashboard 配置
  copy:
    src: grafana/provisioning/dashboards/
    dest: "{{ monitoring_data_dir }}/grafana/provisioning/dashboards"
    mode: 0644
    owner: 472
    group: 472
  register: grafana_dashboard

- name: 複製 Docker Compose 配置
  template:
    src: docker-compose.yml.j2
    dest: "{{ monitoring_data_dir }}/docker-compose.yml"
    mode: 0644
  register: docker_compose_file

- name: 啟動監控服務
  community.docker.docker_compose_v2:
    project_src: "{{ monitoring_data_dir }}"
    state: present
  register: output

- name: 顯示 Docker Compose 服務狀態
  debug:
    var: output

- name: 確保防火牆開放 Prometheus 和 Grafana 端口
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - "{{ prometheus_port }}"
    - "{{ grafana_port }}"
  when: ansible_os_family == "Debian"
